name: laravel-tp

services:
    laravel1:
        build:
            context: .
            dockerfile: dockerfile
        container_name: laravel-1
        depends_on:
            - db
        volumes:
            - ./:/var/www/html/laravel/
        env_file:
            - ./.env
        networks:
            - laravel-network

    laravel2:
        build:
            context: .
            dockerfile: dockerfile
        container_name: laravel-2
        depends_on:
            - db
        volumes:
            - ./:/var/www/html/laravel/
        networks:
            - laravel-network
        env_file:
            - ./.env2

    nginx1:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - .:/var/www/html/laravel/
        env_file:
            - .env
        depends_on:
            - laravel1
        networks:
            - laravel-network
      

    nginx2:
        image: nginx:latest

        ports:
            - "90:80"
        volumes:
            - ./nginx2.conf:/etc/nginx/nginx.conf:ro
            - .:/var/www/html/laravel/
        env_file:
            - .env2
        depends_on:
            - laravel2
        networks:
            - laravel-network
       

    db:
        image: mysql
        container_name: mysql-db
        restart: always
        ports:
            - "3306:3306"
        environment:
            - MYSQL_DATABASE=laravel-db
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_USER=utilisateur
            - MYSQL_PASSWORD=password
        volumes:
            - db-data:/var/lib/mysql
        networks:
            - laravel-network
volumes:
    db-data:

networks:
    laravel-network:
        driver: bridge
